



export const translations = {
  en: {
    landing: {
      title: "Infinite Canvas",
      subtitle: "Describe functionality to generate autonomous React widgets.",
      poweredBy: "Powered by",
      start: "Start Blank Workspace",
      prototype: "Prototype - Google Ai Labs v0.2.5",
      designedFor: "Designed for Everyone",
      blueprints: {
        kanban: { title: "Kanban Board", desc: "Drag-and-drop task management.", prompt: "Create a Kanban board with 'To Do', 'In Progress', and 'Done' columns. Allow adding new cards and dragging them between columns. Use a clean, minimal design." },
        finance: { title: "Finance Tracker", desc: "Visualize expenses with interactive charts.", prompt: "Build a personal finance dashboard. Include a pie chart for expense categories, a list of recent transactions, and a summary of total spending. Use mock data." },
        calendar: { title: "Smart Calendar", desc: "Schedule events with a modern UI.", prompt: "Design a monthly calendar widget. Allow clicking on a day to add an event. Show a list of upcoming events for the selected day." },
        crypto: { title: "Crypto Ticker", desc: "Real-time market data visualization.", prompt: "Create a cryptocurrency dashboard showing Bitcoin, Ethereum, and Solana prices. Use a line chart to simulate price history and display percentage changes. Use mock data." }
      },
      system: {
        online: "System Online",
        missing: "Key Missing"
      }
    },
    workspace: {
      subtitle: "Workspace",
      ready: "Ready",
      presets: "Presets",
      autoLayout: "Auto Layout",
      reset: "Reset",
      zoomOut: "Zoom Out",
      zoomIn: "Zoom In",
      accessibility: "Accessibility",
      theme: "Theme",
      about: "About",
      settings: "Settings",
      aura: "Aura Mode",
      processLog: "System Log",
      setupRequired: "Setup Required",
      setupDesc: "Please configure your API Key to initialize the generation engine.",
      configure: "Configure Interface",
      loading: {
        orchestrator: "Orchestrator",
        architect: "Architect",
        engineer: "Engineer",
        analyzing: "Analyzing requirements...",
        deleting: "Deleting widget...",
        rerolling: "Rerolling entire dashboard reality...",
        designing: "Designing technical specification...",
        adapting: "Adapting template..."
      }
    },
    process: {
      title: "Process Console",
      status: "System Active",
      waiting: "Waiting for Input..."
    },
    command: {
      placeholder: "What would you like to build?",
      generating: "Generating...",
      regenerate: "Regenerate All Widgets",
      execute: "Execute"
    },
    settings: {
      title: "Settings",
      subtitle: "Configure system preferences and behavior",
      tabs: {
        general: "General",
        intelligence: "Intelligence",
        keyboard: "Keyboard"
      },
      language: "Interface Language",
      behavior: "Workspace Behavior",
      snapToGrid: "Snap to Grid",
      snapDesc: "Align widgets automatically when dragging",
      grid: {
        title: "Grid Appearance",
        style: "Pattern Style",
        opacity: "Opacity",
        dots: "Dots",
        lines: "Lines"
      },
      provider: "AI Provider",
      credentials: "Credentials",
      apiKey: "API Key",
      model: "Model Version",
      suggestions: {
          title: "Generative Suggestions (Muse)",
          mode: "Suggestion Mode",
          generative: "Generative (AI)",
          generativeDesc: "Dynamic ideas generated by AI based on context.",
          preselected: "Preselected (Static)",
          preselectedDesc: "Fast, curated list of common app ideas.",
          model: "Suggestion Model"
      },
      save: "Apply Changes",
      cancel: "Cancel",
      changes: "Changes require Apply",
      globalMapping: "Global Mapping",
      browserWarning: "Browser access enabled. Ensure your API key has appropriate permissions for client-side usage.",
      shortcutNote: "Shortcuts use <strong>Mod</strong> to automatically adapt to your OS (Cmd on Mac, Ctrl on Windows).",
      getKey: "Get your key from",
      proTip: "Pro Tip",
      proTipDesc: "Switch providers to test different reasoning models for complex tasks."
    },
    accessibility: {
      title: "Accessibility Tools",
      subtitle: "Customize your experience",
      beta: "Beta Feature",
      voiceDesc: "Voice Access uses semantic tokenization to let you control the interface completely hands-free. Speak commands like 'Click 4' or 'Agent create a chart'.",
      voiceLabel: "Voice Access Mode",
      voiceHelp: "Control the entire interface using voice commands.",
      screenReaderLabel: "Screen Reader Support",
      screenReaderHelp: "Enhance generated widgets with strict ARIA tags and focus management.",
      motionLabel: "Reduce Motion",
      motionHelp: "Disable interface animations and transitions.",
      contrastLabel: "High Contrast",
      contrastHelp: "Increase visual contrast for better readability.",
      textLabel: "Large Text",
      textHelp: "Scale up the text size for the interface.",
      dyslexicLabel: "Dyslexic Friendly",
      dyslexicHelp: "Usa una tipografía más legible.",
      footer: "Preferences are saved automatically to your device."
    },
    intro: {
      initializing: "Initializing Runtime..."
    },
    info: {
      role: "Full Stack Engineer",
      aboutTitle: "About",
      aboutDesc: "Building the next generation of recursive interfaces. Focusing on self-assembling UI/UX and autonomous agent workflows.",
      connect: "Connect",
      portfolio: "Portfolio",
      systemArch: "System Architecture",
      core: "Core",
      runtime: "Runtime",
      status: "Status",
      operational: "Operational"
    },
    help: {
      title: "Keyboard Shortcuts",
      system: "System",
      navigation: "Navigation & View",
      widgets: "Widget Controls",
      footer: "Recursive App Generation System",
      keys: {
        emergency: "Emergency Mode",
        agent: "Focus Agent Input",
        theme: "Toggle Theme",
        help: "Help Menu",
        pan: "Pan Canvas",
        zoomIn: "Zoom In",
        zoomOut: "Zoom Out",
        reset: "Reset View",
        autoLayout: "Auto Layout",
        select: "Select Widget",
        delete: "Delete Widget",
        deselect: "Deselect All",
        nudge: "Nudge Position",
        fastNudge: "Fast Nudge"
      }
    },
    emergency: {
      breatheIn: "Breathe In",
      hold: "Hold",
      breatheOut: "Breathe Out",
      needElse: "I need something else",
      quiet: "Quiet",
      sound: "Sound",
      focus: "Focus",
      ok: "I'm Okay Now"
    },
    contextMenu: {
      newBlueprint: "New Blueprint",
      commandList: "Command List",
      wipe: "Wipe Dashboard",
      regenerate: "Regenerate Widget",
      delete: "Delete Widget",
      researcherSuite: "Researcher Suite",
      designerSuite: "Designer Suite",
      analystSuite: "Analyst Suite",
      productivitySuite: "Productivity Suite",
      arcadeSuite: "Arcade Suite",
      confirmWipe: "Are you sure you want to remove all widgets?"
    },
    manual: {
      title: "System Manual",
      missionTitle: "Mission Profile",
      missionText1: "You are operating",
      missionText2: "Unlike static apps, this system builds itself. Describe a tool, and the AI Architect constructs it instantly using React, Tailwind, and Recharts.",
      controlsTitle: "Controls",
      capabilitiesTitle: "Capabilities",
      secure: "Secure"
    },
    muse: {
      title: "The Muse",
      subtitle: "AI Dream Engine",
      placeholder: "What do you want to create?",
      quickStarts: "Quick Starts",
      build: "Build",
      tags: ['Personal Finance', 'Retro Arcade', 'Markdown Kanban', 'Pomodoro Timer']
    },
    widgetControls: {
      close: "Close",
      expand: "Expand",
      collapse: "Collapse",
      regenerate: "Regenerate"
    },
    voiceHud: {
      active: "Voice Access Active",
      error: "System Error",
      listening: "Listening for commands...",
      last: "Last",
      click: "Click",
      scrollDown: "Scroll Down",
      emergency: "Emergency Mode"
    },
    templates: {
      dashboard: {
        title: "Analytics Overview",
        subtitle: "Real-time performance metrics",
        revenue: "Total Revenue",
        users: "Active Users",
        profit: "Net Profit",
        trends: "Weekly Trends",
        days: "['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']"
      },
      chat: {
        title: "AI Assistant",
        status: "Online",
        placeholder: "Type a message...",
        welcome: "How can I help you today?",
        thinking: "Thinking..."
      },
      list: {
        title: "Tasks",
        filter: "Filter items...",
        remaining: "remaining",
        done: "done",
        items: [
          { title: "Review System Architecture", tag: "High" },
          { title: "Update Documentation", tag: "Medium" },
          { title: "Client Meeting", tag: "Low" }
        ]
      },
      tool: {
        title: "Tool Title",
        desc: "Description of what this tool does.",
        label: "Input Label",
        placeholder: "Value...",
        calculate: "Calculate",
        output: "Output Result"
      }
    }
  },
  es: {
    landing: {
      title: "Lienzo Infinito",
      subtitle: "Describe la funcionalidad para generar widgets React autónomos.",
      poweredBy: "Impulsado por",
      start: "Iniciar Espacio en Blanco",
      prototype: "Prototipo - Google Ai Labs v0.2.5",
      designedFor: "Diseñado para Todos",
      blueprints: {
        kanban: { title: "Tablero Kanban", desc: "Gestión de tareas arrastrar y soltar.", prompt: "Crea un tablero Kanban con columnas 'Por Hacer', 'En Progreso' y 'Hecho'. Permite agregar nuevas tarjetas y arrastrarlas entre columnas. Usa un diseño limpio y minimalista." },
        finance: { title: "Rastreador Financiero", desc: "Visualiza gastos con gráficos interactivos.", prompt: "Construye un panel de finanzas personales. Incluye un gráfico circular para categorías de gastos, una lista de transacciones recientes y un resumen del gasto total. Usa datos simulados." },
        calendar: { title: "Calendario Inteligente", desc: "Programa eventos con una UI moderna.", prompt: "Diseña un widget de calendario mensual. Permite hacer clic en un día para agregar un evento. Muestra una lista de próximos eventos para el día seleccionado." },
        crypto: { title: "Ticker Cripto", desc: "Visualización de mercado en tiempo real.", prompt: "Crea un panel de criptomonedas que muestre los precios de Bitcoin, Ethereum y Solana. Usa un gráfico de líneas para simular el historial de precios y mostrar cambios porcentuales. Usa datos simulados." }
      },
      system: {
        online: "Sistema En Línea",
        missing: "Falta Clave"
      }
    },
    workspace: {
      subtitle: "Espacio de Trabajo",
      ready: "Listo",
      presets: "Preajustes",
      autoLayout: "Auto Diseño",
      reset: "Reiniciar",
      zoomOut: "Alejar",
      zoomIn: "Acercar",
      accessibility: "Accesibilidad",
      theme: "Tema",
      about: "Acerca de",
      settings: "Ajustes",
      aura: "Modo Aura",
      processLog: "Registro del Sistema",
      setupRequired: "Configuración Requerida",
      setupDesc: "Por favor configura tu Clave API para inicializar el motor de generación.",
      configure: "Configurar Interfaz",
      loading: {
        orchestrator: "Orquestador",
        architect: "Arquitecto",
        engineer: "Ingeniero",
        analyzing: "Analizando requerimientos...",
        deleting: "Eliminando widget...",
        rerolling: "Re-tirando toda la realidad...",
        designing: "Diseñando especificación técnica...",
        adapting: "Adaptando plantilla..."
      }
    },
    process: {
      title: "Consola de Proceso",
      status: "Sistema Activo",
      waiting: "Esperando Entrada..."
    },
    command: {
      placeholder: "¿Qué te gustaría construir?",
      generating: "Generando...",
      regenerate: "Regenerar Todos los Widgets",
      execute: "Ejecutar"
    },
    settings: {
      title: "Configuración",
      subtitle: "Motor de Inferencia y Entradas",
      tabs: {
        general: "General",
        intelligence: "Inteligencia",
        keyboard: "Teclado"
      },
      language: "Idioma de Interfaz",
      behavior: "Comportamiento",
      snapToGrid: "Ajustar a Cuadrícula",
      snapDesc: "Alinear widgets automáticamente al arrastrar",
      grid: {
        title: "Apariencia de Cuadrícula",
        style: "Estilo de Patrón",
        opacity: "Opacidad",
        dots: "Puntos",
        lines: "Líneas"
      },
      provider: "Proveedor de IA",
      credentials: "Credenciales",
      apiKey: "Clave API",
      model: "Versión del Modelo",
      suggestions: {
          title: "Sugerencias Generativas (Musa)",
          mode: "Modo de Sugerencia",
          generative: "Generativo (IA)",
          generativeDesc: "Ideas dinámicas generadas por IA según el contexto.",
          preselected: "Preseleccionado (Estático)",
          preselectedDesc: "Lista rápida y curada de ideas comunes.",
          model: "Modelo de Sugerencia"
      },
      save: "Aplicar Cambios",
      cancel: "Cancelar",
      changes: "Cambios requieren Aplicar",
      globalMapping: "Mapeo Global",
      browserWarning: "Acceso al navegador habilitado. Asegúrate de que tu clave API tenga permisos para uso del lado del cliente.",
      shortcutNote: "Los atajos usan <strong>Mod</strong> para adaptarse automáticamente a tu SO (Cmd en Mac, Ctrl en Windows).",
      getKey: "Obtén tu clave en",
      proTip: "Consejo Pro",
      proTipDesc: "Cambia de proveedor para probar diferentes modelos de razonamiento en tareas complejas."
    },
    accessibility: {
      title: "Herramientas de Accesibilidad",
      subtitle: "Personaliza tu experiencia",
      beta: "Función Beta",
      voiceDesc: "Voice Access usa tokenización semántica para permitirte controlar la interfaz completamente manos libres. Di comandos como 'Click 4' o 'Agent crea un gráfico'.",
      voiceLabel: "Modo de Acceso por Voz",
      voiceHelp: "Controla toda la interfaz usando comandos de voz.",
      screenReaderLabel: "Soporte de Lector de Pantalla",
      screenReaderHelp: "Mejora los widgets generados con etiquetas ARIA estrictas y gestión de foco.",
      motionLabel: "Reducir Movimiento",
      motionHelp: "Deshabilita animaciones y transiciones de la interfaz.",
      contrastLabel: "Alto Contraste",
      contrastHelp: "Aumenta el contraste visual para mejor legibilidad.",
      textLabel: "Texto Grande",
      textHelp: "Aumenta el tamaño del texto para la interfaz.",
      dyslexicLabel: "Amigable para Dislexia",
      dyslexicHelp: "Usa una tipografía más legible.",
      footer: "Las preferencias se guardan automáticamente en tu dispositivo."
    },
    intro: {
      initializing: "Inicializando Tiempo de Ejecución..."
    },
    info: {
      role: "Ingeniero Full Stack",
      aboutTitle: "Acerca de",
      aboutDesc: "Construyendo la próxima generación de interfaces recursivas. Enfocado en UI/UX auto-ensamblable y flujos de trabajo de agentes autónomos.",
      connect: "Conectar",
      portfolio: "Portafolio",
      systemArch: "Arquitectura del Sistema",
      core: "Núcleo",
      runtime: "Tiempo de Ejecución",
      status: "Estado",
      operational: "Operacional"
    },
    help: {
      title: "Atajos de Teclado",
      system: "Sistema",
      navigation: "Navegación y Vista",
      widgets: "Controles de Widget",
      footer: "Sistema de Generación de Aplicaciones Recursivas",
      keys: {
        emergency: "Modo de Emergencia",
        agent: "Barra de Comandos",
        theme: "Cambiar Tema",
        help: "Menú de Ayuda",
        pan: "Mover Lienzo",
        zoomIn: "Acercar",
        zoomOut: "Alejar",
        reset: "Reiniciar Vista",
        autoLayout: "Auto Diseño",
        select: "Seleccionar Widget",
        delete: "Eliminar Widget",
        deselect: "Deseleccionar Todo",
        nudge: "Mover Posición",
        fastNudge: "Mover Rápido"
      }
    },
    emergency: {
      breatheIn: "Inhala",
      hold: "Mantén",
      breatheOut: "Exhala",
      needElse: "Necesito otra cosa",
      quiet: "Silencio",
      sound: "Sonido",
      focus: "Enfoque",
      ok: "Estoy Bien"
    },
    contextMenu: {
      newBlueprint: "Nuevo Plano",
      commandList: "Lista de Comandos",
      wipe: "Limpiar Tablero",
      regenerate: "Regenerar Widget",
      delete: "Eliminar Widget",
      researcherSuite: "Suite de Investigador",
      designerSuite: "Suite de Diseño",
      analystSuite: "Suite de Analista",
      productivitySuite: "Suite de Productividad",
      arcadeSuite: "Suite Arcade",
      confirmWipe: "¿Estás seguro de que deseas eliminar todos los widgets?"
    },
    manual: {
      title: "Manual del Sistema",
      missionTitle: "Perfil de Misión",
      missionText1: "Estás operando",
      missionText2: "A diferencia de las apps estáticas, este sistema se construye solo. Describe una herramienta y el Arquitecto de IA la construye al instante usando React, Tailwind y Recharts.",
      controlsTitle: "Controles",
      capabilitiesTitle: "Capacidades",
      secure: "Seguro"
    },
    muse: {
      title: "La Musa",
      subtitle: "Motor de Sueños IA",
      placeholder: "¿Qué quieres crear?",
      quickStarts: "Inicio Rápido",
      build: "Construir",
      tags: ['Finanzas (Mock)', 'Juego Arcade', 'Kanban Markdown', 'Temporizador Pomodoro']
    },
    widgetControls: {
      close: "Cerrar",
      expand: "Expandir",
      collapse: "Colapsar",
      regenerate: "Regenerar"
    },
    voiceHud: {
      active: "Acceso por Voz Activo",
      error: "Error del Sistema",
      listening: "Escuchando comandos...",
      last: "Último",
      click: "Clic",
      scrollDown: "Bajar",
      emergency: "Modo Emergencia"
    },
    templates: {
      dashboard: {
        title: "Resumen Analítico",
        subtitle: "Métricas de rendimiento en tiempo real",
        revenue: "Ingresos Totales",
        users: "Usuarios Activos",
        profit: "Beneficio Neto",
        trends: "Tendencias Semanales",
        days: "['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom']"
      },
      chat: {
        title: "Asistente IA",
        status: "En línea",
        placeholder: "Escribe un mensaje...",
        welcome: "¿Cómo puedo ayudarte hoy?",
        thinking: "Pensando..."
      },
      list: {
        title: "Tareas",
        filter: "Filtrar elementos...",
        remaining: "restantes",
        done: "hecho",
        items: [
          { title: "Revisar Arquitectura del Sistema", tag: "Alta" },
          { title: "Actualizar Documentación", tag: "Media" },
          { title: "Reunión con Cliente", tag: "Baja" }
        ]
      },
      tool: {
        title: "Título de Herramienta",
        desc: "Descripción de lo que hace esta herramienta.",
        label: "Etiqueta de Entrada",
        placeholder: "Valor...",
        calculate: "Calcular",
        output: "Resultado"
      }
    }
  }
};
